language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxcb-image0
  - sudo apt-get install -y libxcb-randr0
  - sudo apt-get install -y libudev0
  - sudo apt-get install -y libudev1

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - make
  - ./tests