language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxcb-image0 libxcb-randr0 libudev0 libsfml-dev
  
script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - make
  - ./tests