language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsfml-dev libsfml-graphics2 libsfml-window2

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - make
  - ./tests